import './globals.css'
import { Space_Mono } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import Login from '../components/NavLinks'
import NavLinks from '../components/NavLinks'

const spaceMono = Space_Mono({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
})

const spaceMonoBig = Space_Mono({
  weight: '700',
  subsets: ['latin'],
  style: 'normal',
})

export const metadata = {
  title: 'Readr',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-mywhite text-myblack w-screen">
      <UserProvider>
        <body className="flex flex-col min-h-screen justify-between">
          <div className={spaceMonoBig.className}>
            <nav className="bg-myblack text-myblack flex lg:justify-between lg:px-32 xl:px-40 flex-col lg:flex-row">
              <a
                className="hover:opacity-50 flex justify-center lg:justify-start"
                href="/"
              >
                <img
                  src="/readr-header-logo.png"
                  alt="readr logo"
                  className="lg:h-36 h-28 py-3"
                />
              </a>
              <div className="flex justify-center">
                <NavLinks />
              </div>
            </nav>
            <div className="bg-mywhite text-myblack relative h-auto justify-start">
              <div>{children}</div>
            </div>
            <footer className="bg-myblack text-mywhite sm:px-28 lg:px-32 xl:px-40 flex flex-col justify-center">
              <div className="flex md:flex-row flex-col md:w-full md:justify-between justify-center">
                <a
                  href="/"
                  className="hover:opacity-50 flex justify-center lg:justify-start"
                >
                  <img
                    src="/readr-header-logo.png"
                    alt="readr logo"
                    className="h-24 mb-3 md:mb-5 mt-6 lg:h-28"
                  />
                </a>
                <div className="flex row-auto lg:w-full justify-center lg:justify-end pb-5 md:pb-0">
                  <a
                    href="https://www.instagram.com/readrco/"
                    target="_blank"
                    className="flex justify-center py-0 my-auto  hover:opacity-50"
                  >
                    <img
                      src="/instagram.svg"
                      alt="instagram icon"
                      className="px-4 md:w-16 w-14"
                    ></img>
                  </a>
                  <a
                    href="#"
                    target="_blank"
                    className="flex justify-center py-0 my-auto hover:opacity-50"
                  >
                    <img
                      src="/tiktok.svg"
                      alt="tiktok icon"
                      className="p-4 md:w-16 w-14"
                    ></img>
                  </a>
                  <a
                    href="#"
                    target="_blank"
                    className="flex justify-center py-0 my-auto hover:opacity-50"
                  >
                    <img
                      src="/twitter.svg"
                      alt="twitter icon"
                      className="p-4 md:w-16 w-14"
                    ></img>
                  </a>
                </div>
              </div>
              <div className="w-auto mx-8 h-1 bg-mywhite opacity-5 sm:mx-0 lg:h-1 lg:my-0 lg:w-auto"></div>
              <div className="w-full flex flex-col py-8 justify-center lg:justify-between text-small text-center lg:w-full sm:flex-row sm:justify-between items-center">
                <p className="py-2">©Copyright 2023 Readr</p>
                <div className="flex md:flex-row md:justify-end flex-col justify-center">
                  <a href="#" className="md:pr-4 py-2 hover:text-myred">
                    Privacy Policy
                  </a>
                  <a href="#" className="md:pl-4 py-2 hover:text-myred">
                    Cookie Policy
                  </a>
                </div>
              </div>
            </footer>
          </div>
        </body>
      </UserProvider>
    </html>
  )
}
