import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Reading',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>My Reading Tracker</h1>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/read-books">Read</Link>
          <Link href="/tbr-books">To Be Read</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
